# Generated by Django 2.2 on 2020-01-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20200114_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=2550, null=True),
        ),
    ]
